server: papera
virtualenv_home: /home/gabriel/cmipstatusenv
site_root: /home/gabriel/cmipsite/
database_file: /home/gabriel/cmipsite/inpedb.sqlite

imgs_info:
    infotype:
        mean_sst: mean_sst
        mean_sss: mean_sss

    regions:
        SA: SA
        SH: SH
        GT: GT
        NH: NH
        GB: GB
        TP: TP
        TA: TA

    ensembled:
        variables:
            - sss
            - sst
            - taux
            - tauy
            - u
            - v
        statistics:
            - annualmean
            - gb_series
            - variance
            - eof
        scalars:
            - eta_nonsteric
            - eta_steric
            - total_eta
            - pme
            - salt_total
            - temp_total
            - total_ke
            - total_pe

    figs_url: http://ftp-supercomputacao.inpe.br/public/g.marcondes/cmip_evaluation/{0}/figures/
    local_figs: /media/{0}/figures
    local_new_figs: media/exp_analysis_figures/{0}
    figs_file: '{0}_{1}_{2}_{3}_{4}.gif'
    figs_log: http://ftp-supercomputacao.inpe.br/public/g.marcondes/cmip_evaluation/{0}/figures/log.yaml
    local_logs: media/{0}/figures/log.yaml

CO2_info:
    fixed:
        - cmp005
        - cmp007
        - cmp009
        - cmp011
        - cmp013
        - cmp015
        - cmp017
        - cmp019
        - cmp020
        - cmp021        
    mauna-loa:
        - cmp004
        - cmp006
        - cmp008
        - cmp010
        - cmp012
        - cmp014
        - cmp016
        - cmp018
        - cmp022
        - cmp023
    increment:
        - cmp003

qstat_log: /home/gabriel/cmipsite/cmipstatus/cmip_bots/fetched_data/cmip_evaluation/running_stats.txt
restartlist_template: /home/gabriel/cmipsite/cmipstatus/cmip_bots/fetched_data/cmip_evaluation/RESTARTLIST.{0}.tmp
